# Array creation

In [29]:
import numpy as np

In [30]:
array1=np.array([1,2,3],dtype='int')

In [31]:
array1

array([1, 2, 3])

In [32]:
zeros=np.zeros((3,3),dtype='int')

In [33]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
ones=np.ones((3,3),dtype='int')

In [35]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
full=np.full((2,3),5)

In [37]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [43]:
identity= np.identity(3,dtype='int')

In [44]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [50]:
eye=np.eye(3,3,-1)

In [51]:
eye

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

Arang function

In [52]:
arange=np.arange(1,10,2)

In [53]:
arange


array([1, 3, 5, 7, 9])

In [54]:
linspace=np.linspace(1,5,10)


In [56]:
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [57]:
linspace.size

10

In [59]:
empty=np.empty((1,5))

In [60]:
empty

array([[0.00000000e+000, 1.09934885e-311, 1.09934885e-311,
        1.09934885e-311, 0.00000000e+000]])

In [ ]:
for i in range(5):
    empty[:,i]